config/routes.rb
Rails.application.routes.draw do
  root to: 'root#show'

  namespace :users do
    get 'sign_in', to: 'sessions#new'
    get 'confirmed', to: 'sessions#new'
    get 'sign_up', to: 'registrations#new'
    get 'confirmations', to: 'confirmations#new'
  end

  get 'input', to: 'records#new'
  get 'mypage', to: 'mypage#show'
  get 'settings', to: 'settings#show'
  get 'categories', to: 'categories#index'
  get 'breakdowns', to: 'breakdowns#index'
  get 'places', to: 'places#index'
  get 'tags', to: 'tags#index'

  namespace :admin, module: :admin_page do
    get 'users', to: 'users#show'
  end

  scope :api do
    mount_devise_token_auth_for 'User', at: 'auth', controllers: {
      confirmations: 'api/auth/confirmations'
    }
  end

  namespace :api do
    resource :user, only: %i[show update]
    resource :profile, only: %i[show update]
    resources :categories, only: %i[index show create update destroy]
    resources :breakdowns, only: %i[index create update destroy]
    resources :places, only: %i[index create update destroy] do
      resources :categories, only: %i[index create], module: :place
    end
    resources :tags, only: %i[index create update destroy]
    resources :records, only: %i[index create update destroy]
    resources :dashboards, param: :year, only: %i[index show update] do
      resources :categories, only: %i[show], module: :dashboards
    end
    resource :tutorial, only: %i[show]
    resources :assets_accounts, only: %i[index create update destroy]
    resources :piggy_banks do
      resources :piggy_items, only: %i[index create update destroy]
    end

    namespace :admin do
      resources :users, only: %i[index]
    end
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  protect_from_forgery unless: -> { request.format.json? }

  # TODO: notify to slack
end

app/views/application/_error_messages.slim
- if resource.errors.present?
  .validation-error-messages-field
    - resource.errors.full_messages.each do |message|
      small
        i.fas.fa-exclamation-circle.left-icon
        = message

app/views/application/_footer.slim
footer.footer
  small.copyright
    = 'Copyright © 2004-2021 @kae_kasui All Rights Reserved.'

app/views/application/_header.slim
header.header
  nav.nav-brand
    = image_pack_tag 'pig.gif', class: 'brand-image'
    = link_to root_path, class: 'top-link'
      span.brand-name
        = t('brand_name')
  = react_component('HeaderMenu')
  /nav.nav-menu
    ul.menu
      li
        = link_to root_path, class: 'menu-link'
          i.fas.fa-home.left-icon
          = t('menu.home')
    ul.right-menu
      - if user_signed_in?
        li
          = link_to mypage_path, class: 'menu-link'
            i.fas.fa-user.left-icon
            = t('menu.mypage')
        li
          = link_to destroy_user_session_path, class: 'menu-link', method: :delete
            i.fas.fa-sign-out-alt.left-icon
            = t('menu.sign_out')
      - else
        li
          = link_to new_user_session_path, class: 'menu-link'
            i.fas.fa-leaf.left-icon
            = t('menu.sign_in')
  .clear

app/views/application/_login_menu.slim
.list-group
  = link_to new_user_session_path, class: 'list-group-item'
    i.fas.fa-leaf.left-icon
    = t('menu.sign_in')
  = link_to new_user_registration_path, class: 'list-group-item'
    i.fas.fa-heart.left-icon
    = t('menu.sign_up')

app/views/application/_mypage_menu.slim
.list-group
  = link_to mypage_path, class: 'list-group-item'
    i.fas.fa-user-shield.left-icon
    = t('menu.mypage_top')

.menu-card
  ul.list
    /li.list-item
      label = User.human_attribute_name(:email)
      p.value = current_user.email
    /li.list-item
      label = I18n.t('label.option_names')
      p.value = current_user.options_list

app/views/application/_notification.slim
- flash.each do |key, value|
  .row.flex-end
    .notification-field{class="#{key}"}
      = content_tag(:span) do
        i.fas.fa-exclamation-circle.left-icon
        = value